const usersMock = [
  {
    name: 'Usuario 1',
    email: 'usuario1@gmail.com',
    startDay: '01/01',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 2',
    email: 'usuario2@gmail.com',
    startDay: '02/02',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 3',
    email: 'usuario3@gmail.com',
    startDay: '03/03',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 4',
    email: 'usuario4@gmail.com',
    startDay: '04/04',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 5',
    email: 'usuario5@gmail.com',
    startDay: '05/05',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 6',
    email: 'usuario6@gmail.com',
    startDay: '06/06',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 7',
    email: 'usuario7@gmail.com',
    startDay: '07/07',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 8',
    email: 'usuario8@gmail.com',
    startDay: '08/08',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 9',
    email: 'usuario9@gmail.com',
    startDay: '09/09',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 10',
    email: 'usuario10@gmail.com',
    startDay: '10/10',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 11',
    email: 'usuario11@gmail.com',
    startDay: '11/11',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 12',
    email: 'usuario12@gmail.com',
    startDay: '12/12',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 13',
    email: 'usuario13@gmail.com',
    startDay: '13/13',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 14',
    email: 'usuario14@gmail.com',
    startDay: '14/14',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 15',
    email: 'usuario8@gmail.com',
    startDay: '15/15',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 16',
    email: 'usuario16@gmail.com',
    startDay: '16/16',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 17',
    email: 'usuario8@gmail.com',
    startDay: '17/17',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 18',
    email: 'usuario18@gmail.com',
    startDay: '18/18',
    type: 'Usuário',
    status: 'Ativo',
  },
  {
    name: 'Usuario 19',
    email: 'usuario8@gmail.com',
    startDay: '19/19',
    type: 'Usuário',
    status: 'Ativo',
  },
]

export default usersMock
